# -*- coding: utf-8 -*-
"""Streamlit_App1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDIGD_1MIK6qhc9uYxGK7RZtCIXvQVPN
"""

import streamlit as st
import joblib

# Load model and vectorizer
model = joblib.load("spam_emails_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# UI Title
st.title("📧 Email Spam Classifier")

# Input
email = st.text_area("Enter the email content here:")

if st.button("Predict"):
    clean_email = email.lower().strip()
    vectorized = vectorizer.transform([clean_email])
    prediction = model.predict(vectorized)[0]

    if prediction == 1:
        st.error("❌ Spam Email")
    else:
        st.success("✅ Not Spam Email")